# Generated by Django 4.1.7 on 2023-03-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='name',
            new_name='type',
        ),
    ]
