# Generated by Django 4.1.7 on 2023-03-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_api', '0002_rename_name_component_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
